# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://aikindergarten.github.io/transformers_sandbox/"

git_url = "https://github.com/aikindergarten/transformers_sandbox/tree/master/"

def custom_doc_links(name): return None
